# Generated by Django 6.0.1 on 2026-03-02 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='propuestas_imgs/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('publicacion', 'Publicación Normal'), ('oferta', 'Oferta Laboral')], default='publicacion', max_length=20)),
                ('descripcion_puesto', models.TextField(blank=True, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('puesto', models.CharField(blank=True, max_length=150, null=True)),
                ('horas_laborales', models.CharField(blank=True, help_text='Ej: 40 horas semanales', max_length=50, null=True)),
                ('requerimientos', models.TextField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_oferta', models.CharField(blank=True, choices=[('abierta', 'Abierta / Recibiendo CVs'), ('cerrada', 'Cerrada / Finalizada')], default='abierta', max_length=20, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
