# Generated by Django 6.0.1 on 2026-03-03 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='job_opportunities_imgs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity_type', models.CharField(choices=[('post', 'Publicación Normal'), ('job_offer', 'Oferta Laboral')], default='post', max_length=20)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('position', models.CharField(blank=True, max_length=150, null=True)),
                ('working_hours', models.CharField(blank=True, help_text='Ej: 40 horas semanales', max_length=50, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('offer_status', models.CharField(blank=True, choices=[('open', 'Abierta / Recibiendo CVs'), ('closed', 'Cerrada / Finalizada')], default='open', max_length=20, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Propuesta',
        ),
    ]
