services:
    db:
        image: alpine
        volumes:
            - sqlite_data:/data
        command: tail -f /dev/null
    web:
        build: .
        command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/app
            - sqlite_data:/data
        ports:
            - '8000:8000'

volumes:
    sqlite_data:
